eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        registry-fetch-interval-seconds: 8

    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 4
        lease-expiration-duration-in-seconds: 12


server:
    port: 8765

spring:
    application:
        name: service-feign
    redis:
        host: localhost
        port: 6379
        #password=bigdata123
        #database=15
        timeout: 5000
        pool:
            maxTotal: 8
            maxWaitMillis: 1000

bizcorn:
    session:
        timeout: 1800
        prefix: uid
        cookie:
            name: session
            user: uid
        attribute:
            user: user
            timeout: timeout

feign:
    hystrix:
        enabled: true
        #使用apache的httpclient，连接池，替换feign原生的httpclient
    httpclient:
        enabled=true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

logging:
    level:
        root: WARN
        org.springframework.web: INFO
        com.memorynotfound: DEBUG
        allein.servicefeign: DEBUG