eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        registry-fetch-interval-seconds: 8

    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 4
        lease-expiration-duration-in-seconds: 12


server:
    port: 8765



spring:
    application:
        name: service-feign
    cloud:
        config:
            label: master
            profile: dev
        discovery:
            enabled: true
            service-id: config-server
#      uri: http://localhost:8888/
        stream:
            kafka:
                binder:
                    brokers: 192.168.2.233:9092
                    zk-nodes: 192.168.2.233:2181
    kafka:
        bootstrap-servers: 192.168.2.233:9092
        template:
            default-topic: bizcorn-user
        listener:
            concurrency: 3
        producer:
            batch-size: 1000
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: bizcorn
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    redis:
        host: localhost
        port: 6379
        #password=bigdata123
        #database=15
        timeout: 5000
        pool:
            maxTotal: 8
            maxWaitMillis: 1000

bizcorn:
    session:
        timeout: 1800
        prefix: uid
        cookie:
            name: session
            user: uid
        attribute:
            user: user
            timeout: timeout
hystrix:
   command:
       default:
           execution:
               isolation:
                   thread:
                       timeoutInMilliseconds: 5000
#               timeout:
#                   enabled: false
feign:
    hystrix:
        enabled: true


        #使用apache的httpclient，连接池，替换feign原生的httpclient
    httpclient:
        enabled: true
        connection-timeout: 5000
        read_timeout: 5000
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

logging:
    level:
        root: INFO
        org.springframework.web: INFO
        com.memorynotfound: INFO
        allein.bizcorn.servicefeign: DEBUG