package allein.model.exception;

public enum ExceptionEnum {

    NOT_LOG_IN("1009", "登录验证失败,请重新登录"),
    NOT_AUHTORIZED("1010", "权限受限"),

    INVEST_USE_BONUS_PAY_FAIL("117", "投资存管项目使用礼金账户记账失败"),
    INVEST_USE_BONUS_CANCEL_PAY_FAIL(
            "118", "撤销投资存管项目使用礼金记账失败"),
    USER_ACCOUNT_ID_INVALID("1000",
            "用户id获取失败"),
    ORDER_NOT_EXIST("1001", "没有对应的订单信息"),
    USER_QUERY_INVESTOR_PROHIBITED(
            "1006", "不能查普通投资者"),
    USER_DEAL_PASSWORD_INVALID("1999", "交易密码不正确"),

    WCTL_SESSION_FIND_USER_ID_ERROR("1000", "用户id获取失败"),

    USER_ESCROW_ACCOUNT_ALREADY_EXISTS("1001", "用户已经开户完成"),
    USER_ESCROW_ACCOUNT_ALREADY_EXISTS_ID(
            "1002", "此身份证已经开户成功"),
    USER_MOBILE_NOT_AUTHENTICATED("1003",
            "用户手机号未认证"),
    USER_ACCOUNT_AUTO_BID_NOT_AUTH("1010", "存管账户未授权自动投标"),
    USER_ACCOUNT_AUTO_CREDIT_INVEST_NOT_AUTH(
            "1011", "存管账户未授权自动债转"),
    INVEST_SECTION_NOT_EXIST("2001",
            "该投资项目子包不存在"),
    INVEST_PROJECT_NOT_EXISTS("1100", "该投资项目不存在"),
    INVEST_PROJECT_TYPE_UNMATCH(
            "1102", "该投资项目类型错误"),
    INVEST_RECORD_NOT_EXIST("1110", "该投资记录不存在"),
    CREDIT_INVEST_AMOUNT_OVER("2983",
            "转让项目回款后债权不足,请稍后重试！"),
    INVEST_RECORD_NOT_IN_PORCESSING(
            "1111", "该投资记录不是在投资中的状态"),
    INVEST_LOAN_TRANSFER_PROHIBITED_WHILE_REFUNDING("2984",
            "转让项目回款期间暂停投资,请明日尝试！"),
    INVEST_LOAN_TRANSFER_WHOLE("2985",
            "此种转让项目需要一次性买断！"),
    INVEST_LOAN_REFUND_IN_TRANSFERING("2986",
            "转让项目回款期间禁止投标,请稍后重试！"),
    INVEST_DURING_CLOSED_PERIOD("2987",
            "不能在交易关闭时间段投资"),
    INVEST_LOANER_ESW_ACCOUNT_INVALID("2988",
            "融资人存管账户异常"),
    INVEST_SAME_LOANER_AND_INVESTOR("2989",
            "不能投资本人的借贷项目"),
    CREDIT_INVEST_COMPENSATE_CAL_ERROR("2990",
            "转让项目回款期间禁止投标,请稍后重试！"),

    INVEST_RECORD_NOT_BELONG_TO_THIS_USER("2991",
            "非本用户的投资记录"),
    INVEST_VOUCHER_PAY_CANCEL_FAILED("2993",
            "存管投资红包取消失败，待处理"),
    INVEST_RECORD_NOT_IN_ESW_SYSTEM("2994",
            "存管投资记录不存在"),
    INVEST_RECORD_HAS_FINISHED("2995", "本地投资记录已经完成"),

    CREDIT_INVEST_CANNOT_CANCEL("2995", "存管债转记录不可撤销"),

    INVEST_SECTON_LOAN_LEFT_QUOTA_INSURFFICIENT("1140", "项目余额不足"),

    AUTO_INVEST_KEEP_MONEY_ERROR("3333", "投资金额超出账户保留金额"),

    INVEST_BONUS_ISSUE_ERROR("2997",
            "投资使用红包发放出错"),
    INVEST_UNDERLOAN_INSERT_ERROR("2998", "投资记账出错"),
    INVEST_PROJECT_SECTION_TYPE_UNMATCH(
            "2999", "该投资项目子包类型错误"),

    USER_IDENTIFICATION_NOT_AUTHENTICATED("1010", "用户身份未认证"),
    USER_BANK_CARD_NOT_BINDED(
            "1011", "用户银行卡未绑定"),

    USER_ACCOUNT_BALANCE_INSUFFICIENT("1101", "存管账户可用余额不足"),

    USER_ACCOUNT_IN_BATCH_PROCESSING(
            "2013", "存管账户有未决的批处理事务，限制出金操作"),

    INVEST_ORIGIN_REQUEST_NOT_FOUND(
            "2996", "存管投资原始请求记录未找到"),
    SMS_CAPTCHA_INVALID("2010", "验证码验证失败"),
    MOBILE_NUMBER_INVALID("2011", "手机号码格式错误"),
    ESCROW_INVEST_BONUS_ISSUE_FAIL("2012", "投资前置红包发送失败"),
    ESCROW_INVEST_CHARGE_FAIL("2009", "债转项目资不抵债，不能投资"),
    ORIGIN_REQUEST_NOT_FOUND(
            "9998", "原始请求记录未找到"),
    USER_ACCOUNT_NOT_EXIST("9999",
            "用户账户不存在"),
    USER_NOT_LOGIN("1009",
            "用户未登录"),
    ESCROW_SIGNATURE_FAILURE("10001", "存管签名错误"),
    ESCROW_REQUEST_FAILURE(
            "10002", "存管请求失败"),
    ESCROW_SERVER_CONNECT_TIMEOUT("10003",
            "存管服务器连接超时"),
    ESCROW_SOCKET_READ_TIMEOUT("10008", "存管服务器读取超时"),
    ESCROW_JSON_DECODE_FAILURE(
            "10004", "存管返回的json数据解析失败"),
    ESCROW_SIGNATURE_INVALID("10005",
            "存管验签错误"),
    ESCROW_RESPONSE_INVALID("10006", "存管返回消息格式错误"),

    ESCROW_RESPONSE_MESSAGE_INVALID(
            "10007", "存管返回消息内容错误"),

    ESCROW_NO_RESPONSE("10009", "存管返回消息内容错误"),
    ESCROW_SYSTEM_BONUS_ACCOUNT_ERROR(
            "10010", "系统红包账号配置错误"),
    ESCROW_SYSTEM_FEE_ACCOUNT_ERROR("10011",
            "系统手续费账号配置错误"),
    ESCROW_RET_DIRECTOR_NOT_FOUND("10012",
            "页面返回请求未找到相应的处理器"),
    ESCROW_ACCOUNT_OPEN_FRENQUENCY_OVER("11000", "存管账户操作过于频繁！"),
    ESCROW_ACCOUNT_NOT_EXIST("11001", "存管账户未开立！"),
    ESCROW_ACCOUNT_PASSWORD_NOT_SET(
            "11002", "存管账户未设置密码！"),
    ESCROW_ACCOUNT_NOT_BIND_CARD("11003",
            "存管账户未绑定银行卡！"),
    ESCROW_ACCOUNT_BIND_CARD_CHANGED("11004",
            "存管账户绑定银行卡已经改变，需要解绑原卡后重新绑定！"),

    ESCROW_ACCOUNT_AUTO_CREDIT_INVEST_NOT_AUTH("11005", "存管账户自动债权转让未签约！"),
    ESCROW_ACCOUNT_AUTO_CREDIT_INVEST_AUTH_ORDERID_ERROR(
            "11006", "自动债转签约订单号错误！"),

    ESCROW_ACCOUNT_AUTO_BID_NOT_AUTH("11007", "存管账户自动投资未签约！"),
    ESCROW_ACCOUNT_AUTO_BID_AUTH_ORDERID_ERROR(
            "11008", "自动债转签约订单号错误！"),

    ESCROW_ACCOUNT_SYNC_FRENQUENCY_OVER("11010", "存管账户同步调用过于频繁，请稍后再试"),
    ESCROW_ACCOUNT_PASSWORD_HAS_SETTED(
            "11011", "存管户的密码已经设定过！"),

    ESCROW_LEGACY_ACCOUNT_BALANCE_INSUFFICIENT("11012", "原系统账号余额不足"),
    ESCROW_MONEY_TRANSFER_RECORD_INSER_FAIL("11013", "插入资金转移记录失败"),

    ESCROW_FILE_DOWNLOAD_FAIL("12001", "存管文件下载请求失败"),
    ESCROW_FILE_DOWNLOAD_MD5_VERIFY_FAIL(
            "12002", "存管文件下载md5完整性验证失败"),

    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_9111("9111", "未知错误"),
    ESCROW_JX_RESPONSE_CODE_CERTIFICATION_FAIL(
            "9900", "认证失败"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_9902("9902",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_9904("9904", "未知错误"),
    ESCROW_JX_RESPONSE_CODE_PASSWORD_ERROR(
            "9908", "密码错误"),
    ESCROW_JX_RESPONSE_CODE_FUNCTION_NOT_APPROVED(
            "9910", "未开通此功能"),
    ESCROW_JX_RESPONSE_CODE_TOO_MANY_PASSWORD_MISINPUT(
            "9915", "超出最大输入密码次数"),
    ESCROW_JX_RESPONSE_CODE_OP_TIMEOUT("9916",
            "交易超时"),
    ESCROW_JX_RESPONSE_CODE_CARD_ID_NOT_MATCH("9920",
            "银行卡与证件不符"),
    ESCROW_JX_RESPONSE_CODE_CERTIFICATION_FAIL2("9999",
            "认证失败"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_B3CAA007("B3CAA007",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_B3CAA290("B3CAA290",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_B3FF0008("B3FF0008",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_B3FF0009("B3FF0009",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_B3FF0010("B3FF0010",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_B3FF0011("B3FF0011",
            "未知错误"),
    ESCROW_JX_RESPONSE_CODE_CARD_NOT_EXIST("CA000054", "卡号不存在"),
    ESCROW_JX_RESPONSE_CODE_PIN_CODE_FAIL(
            "CA000642", "PIN/PVV/CVV/CVV2调用失败"),
    ESCROW_JX_RESPONSE_CODE_PIN_CODE_VERIFY_FAIL(
            "CA003811", "PIN校验错误"),
    ESCROW_JX_RESPONSE_CODE_CA01("CA01",
            "请联系发卡行"),
    ESCROW_JX_RESPONSE_CODE_ID_LENGTH_INVALID("CA100146",
            "证件号码长度非法"),
    ESCROW_JX_RESPONSE_CODE_CUSTOM_NOT_EXIST("CA100147",
            "此客户不存在"),
    ESCROW_JX_RESPONSE_CODE_ID_TYPE_INVALID("CA100150",
            "证件类型无效"),
    ESCROW_JX_RESPONSE_CODE_ID_TYPE_ERROR("CA100152",
            "证件类型不正确"),
    ESCROW_JX_RESPONSE_CODE_OP_CODE_MISSED("CA100765",
            "请输入交易流水号"),
    ESCROW_JX_RESPONSE_CODE_ID_VERIFY_FAIL("CA100766",
            "身份证(18位)校验位错误"),
    ESCROW_JX_RESPONSE_CODE_OP_MONEY_ERROR(
            "CA100845", "交易金额有误"),
    ESCROW_JX_RESPONSE_CODE_DATE_END_PREV_TO_OPEN(
            "CA100882", "结束日期不得早于开户日期"),
    ESCROW_JX_RESPONSE_CODE_OP_OPTION_INVALID(
            "CA100901", "操作选项错误"),
    ESCROW_JX_RESPONSE_CODE_CARD_CANCELED(
            "CA100911", "卡片已注销"),
    ESCROW_JX_RESPONSE_CODE_ID_VERIFY_FAIL2(
            "CA100922", "身份证(18位)校验位错误"),
    ESCROW_JX_RESPONSE_CODE_TOO_MANY_PASSWORD_MISINPUT_ONEYDAY(
            "CA100976", "今日密码连续错误次数超限"),
    ESCROW_JX_RESPONSE_CODE_TOO_MANY_PASSWORD_MISINPUT_ACC(
            "CA100977", "累计密码连续错误次数超限"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_ALEADY_EXISTS(
            "CA101068", "身份证已在平台正常开户"),
    ESCROW_JX_RESPONSE_CODE_HAS_AUTO_INVEST_CONTRACT(
            "CA101100", "存在未取消的自动投标签约记录"),
    ESCROW_JX_RESPONSE_CODE_AUTO_INVEST_CONTRACT_ID_EXIST(
            "CA101101", "签约流水号已存在"),
    ESCROW_JX_RESPONSE_CODE_AUTO_INVEST_CONTRACT_NOT_EXIST(
            "CA101106", "不存在自动投标签约记录"),
    ESCROW_JX_RESPONSE_CODE_AUTO_INVEST_CONTRACT_CANCELED(
            "CA101107", "自动投标签约记录已取消"),
    ESCROW_JX_RESPONSE_CODE_INTEREST_PAY_DAY_EMPTY(
            "CA101112", "利息每月支付日为空"),
    ESCROW_JX_RESPONSE_CODE_INTEREST_EMPTY(
            "CA101114", "年化收益率为空"),
    ESCROW_JX_RESPONSE_CODE_BALANCE_INSUFFICIENT(
            "CA101121", "账户可用余额不足"),
    ESCROW_JX_RESPONSE_CODE_RECORD_FOR_QUERY_STATUS_INVALID(
            "CA101122", "查询的记录状态非法"),
    ESCROW_JX_RESPONSE_CODE_BID_MONEY_NOT_MATCH_WITH_ORIGINAL_TRADE(
            "CA101127", "投标金额与原交易记录不符"),
    ESCROW_JX_RESPONSE_CODE_APPLY_RECORD_CANNOT_WITHDRAW(
            "CA101128", "只有状态是申购中的记录才能撤销"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_HAS_BOUND_TO_THIS_CARD(
            "CA101131", "电子账号已与该卡号绑定"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_ALREADY_HAS_CONTRACT(
            "CA101132", "电子账号已存在签约关系"),
    ESCROW_JX_RESPONSE_CODE_BIND_RECORD_NOT_FOUND(
            "CA101133", "未找到此卡号对应的电子账户绑定记录"),
    ESCROW_JX_RESPONSE_CODE_CANNOT_UNBIND_WITH_REMAINS(
            "CA101134", "账户余额不为0，不能解除绑定"),
    ESCROW_JX_RESPONSE_CODE_UNCLEAR_DEBTS_EXIST(
            "CA101135", "存在本息未返还的第三方理财产品的记录"),
    ESCROW_JX_RESPONSE_CODE_BID_NOT_EXISTS(
            "CA101141", "投标记录不存在"),
    ESCROW_JX_RESPONSE_CODE_UNDER_AGE(
            "CA101142", "未成年（18岁）控制"),
    ESCROW_JX_RESPONSE_CODE_ID_EXIST_IN_LAUNDRY_LIST(
            "CA101154", "转让登记表中转让申请流水号已存在 "),
    ESCROW_JX_RESPONSE_CODE_TRANSFER_MONEY_EMPTY(
            "CA101156", "转让金额为空"),
    ESCROW_JX_RESPONSE_CODE_ORIGINAL_OP_ACCOUNT_ID_ERROR(
            "CA101166", "原交易申请流水号的电子账号错误"),
    ESCROW_JX_RESPONSE_CODE_BUYER_ACCOUNT_ID_ERROR(
            "CA101168", "承接方电子账号错误"),
    ESCROW_JX_RESPONSE_CODE_SELLER_BALANCE_INSUFFICIENT(
            "CA101172", "资金转出方余额不足"),
    ESCROW_JX_RESPONSE_CODE_OVER_TRANSFER_AMOUNT_LIMIT(
            "CA101184", "累计已转让金额超过总共可转让金额"),
    ESCROW_JX_RESPONSE_CODE_OVER_ORIGNAL_DEBT_MONEY(
            "CA101195", "总共可转让金额必须小于等于原债权金额"),
    ESCROW_JX_RESPONSE_CODE_OP_VERIFICATION_FAIL(
            "CA101207", "平台交易验证未通过"),
    ESCROW_JX_RESPONSE_CODE_MOBILE_NO_EMPTY(
            "CA103742", "请输入手机号"),
    ESCROW_JX_RESPONSE_CODE_BID_NOT_EXISTS2(
            "CA110112", "投标记录不存在"),
    ESCROW_JX_RESPONSE_CODE_NOT_COMPANY_ACCOUNT(
            "CA110136", "非企业账户"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_ALREADY_EXISTS_MOBILE(
            "CA110150", "该手机已申领过电子账号"),
    ESCROW_JX_RESPONSE_CODE_BONUS_ACCOUNT_INSUFFICIENT(
            "CA110217", "红包账户可用余额不足"),
    ESCROW_JX_RESPONSE_CODE_BOUNS_LARGE_THEN_BID_MONEY(
            "CA110218", "抵扣红包金额不能大于投标金额"),
    ESCROW_JX_RESPONSE_CODE_FREEZEN_MONEY_INSUFFICIENT(
            "CA110219", "冻结金额不足"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_NOT_MATCH_FREEZEN_RECORD(
            "CA110226", "电子账户与原冻结记录不符"),
    ESCROW_JX_RESPONSE_CODE_AUTHORIZED_AMOUNT_INSUFFICIENT(
            "CA110228", "本期已授权金额总额不足"),
    ESCROW_JX_RESPONSE_CODE_BORROWER_CARD_ID_NOT_MATCH(
            "CA110250", "上送借款人卡号与标信息借款人帐号不符"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_DEADLINE_NOT_MATCH(
            "CA110265", "请输入项目期限（5846）/产品发行方与标的信息不一致（5805）"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_EXISTS(
            "CA110268", "标的信息已经存在不允许录入（5846）/预期年化率与标的信息不一致（5805)"),
    ESCROW_JX_RESPONSE_CODE_PRODCUT_NOT_ISSUED(
            "CA110270", "只能对已发标的标的信息撤销"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_CANCELED(
            "CA110275", "标的已撤销，不能投标"),
    ESCROW_JX_RESPONSE_CODE_DEBT_AUTO_BUY_CONTRACT_EXISTS(
            "CA110357", "存在未取消的无密债权转让签约记录"),
    ESCROW_JX_RESPONSE_CODE_DEBT_AUTO_BUY_CONTRACT_NOT_MATCH(
            "CA110358", "查到的签约记录为非无密债权转让类型"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CA110407(
            "CA110407", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_PLATFROM_ACCOUNT_CANNOT_BID(
            "CA110438", "平台账户不能进行主动投标"),
    ESCROW_JX_RESPONSE_CODE_PLATFORM_ACCOUNT_CANNOT_ISSUE_PRODUCT(
            "CA110440", "平台账户不能进行标的录入"),
    ESCROW_JX_RESPONSE_CODE_DATE_INVALID(
            "CA12", "日期非法"),
    ESCROW_JX_RESPONSE_CODE_OP_AMOUNT_NOT_MATCH_ORIGNAL(
            "CA13", "交易金额与原交易不匹配"),
    ESCROW_JX_RESPONSE_CODE_CARD_NOT_EXIST2(
            "CA14", "卡号不存在"),
    ESCROW_JX_RESPONSE_CODE_ORIGNAL_OP_NOT_EXIST(
            "CA25", "找不到原交易"),
    ESCROW_JX_RESPONSE_CODE_FUNCTION_NOT_SUPPORT(
            "CA40", "不支持的功能"),
    ESCROW_JX_RESPONSE_CODE_BALANCE_INSUFFICIENT2(
            "CA51", "余额不足"),
    ESCROW_JX_RESPONSE_CODE_PASSWORD_ERROR2("CA55",
            "密码错"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_FROZEN("CA57", "账户已冻结"),
    ESCROW_JX_RESPONSE_CODE_TOO_MANY_PIN_MIS_INPUT(
            "CA75", "超过当日允许的PIN最大试输入次数"),
    ESCROW_JX_RESPONSE_CODE_OP_REPEAT(
            "CA94", "重复交易"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CA99902(
            "CA999002", ""),
    ESCROW_JX_RESPONSE_CODE_FUNCTION_IS_PROHIBITTED(
            "CE999001", "功能受限，交易失败"),
    ESCROW_JX_RESPONSE_CODE_TRANSACTION_HAS_BEEN_ACCEPTED(
            "CE999028", "交易已受理，请稍后查询交易结果"),
    ESCROW_JX_RESPONSE_CODE_DEFAULT_OPTIONS_NOT_CONFIGED(
            " CE999029", "缺省参数未配置"),
    ESCROW_JX_RESPONSE_CODE_CI10("CI10",
            "请联系发卡行"),
    ESCROW_JX_RESPONSE_CODE_SERVER_VERIFICATION_FAIL("CI11",
            "服务器验签失败"),
    ESCROW_JX_RESPONSE_CODE_OP_FAILED("CI60",
            "交易失败，详情请咨询您的发卡行"),
    ESCROW_JX_RESPONSE_CODE_CI61("CI61", "请联系发卡行"),
    ESCROW_JX_RESPONSE_CODE_CI62(
            "CI62", "请联系发卡行"),
    ESCROW_JX_RESPONSE_CODE_CI65("CI65", "请联系发卡行"),
    ESCROW_JX_RESPONSE_CODE_CI66(
            "CI66", "核验身份信息失败，请联系发卡行"),
    ESCROW_JX_RESPONSE_CODE_TOO_MANY_PASSWORD_MISINPUT2(
            "CI67", "密码输入次数超限"),
    ESCROW_JX_RESPONSE_CODE_FUNCTION_NOT_SUPPORT_BY_CARD(
            "CI68", "您的银行卡暂不支持该业务，请向您的银行或95516咨询"),
    ESCROW_JX_RESPONSE_CODE_AUTHORIZED_PAY_NOT_OPEN(
            "CI77", "银行卡未开通认证支付"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CI999001(
            "CI999001", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_FAIL_OVER_6_TIMES(
            "CP0015", "充值连续6次都失败"),
    ESCROW_JX_RESPONSE_CODE_ID_FORMAT_INVALID(
            "CP0016", "身份证格式错误"),
    ESCROW_JX_RESPONSE_CODE_ISSUE_BANK_ERROR(
            "CP012001", "查开户方原因"),
    ESCROW_JX_RESPONSE_CODE_TRANSACTION_IN_PROCESS(
            "CP2000", "交易正在处理，请稍后查询结果"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP2001(
            "CP2001", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP2031(
            "CP2031", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP2051(
            "CP2051", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP2061(
            "CP2061", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP2094(
            "CP2094", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP20E2(
            "CP20E2", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP20PD(
            "CP20PD", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP20PS(
            "CP20PS", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP312031(
            "CP312031", "超过支付额度"),
    ESCROW_JX_RESPONSE_CODE_MISSED_CARD(
            "CP412041", "挂失卡"),
    ESCROW_JX_RESPONSE_CODE_TRANSACTION_PROCESSED_OR_RECEVIED(
            "CP452000", "处理完成或接收成功"),
    ESCROW_JX_RESPONSE_CODE_BALANCE_INSUFFICIENT3(
            "CP512051", "余额不足"),
    ESCROW_JX_RESPONSE_CODE_OVER_WITHDRAW_LIMIT(
            "CP612061", "超出提款限额"),
    ESCROW_JX_RESPONSE_CODE_OP_REPEAT2(
            "CP942094", "重复业务"),
    ESCROW_JX_RESPONSE_CODE_OP_FAIL("CP9904",
            "交易失败"),
    ESCROW_JX_RESPONSE_CODE_FUNCTION_NOT_APPROVED2("CP9910",
            "未开通此功能"),
    ESCROW_JX_RESPONSE_CODE_TOO_MANY_PASSWORD_MISINPUT3(
            "CP9915", "超出最大输入密码次数"),
    ESCROW_JX_RESPONSE_CODE_OP_REPEAT3(
            "CP9917", "交易重复"),
    ESCROW_JX_RESPONSE_CODE_BANK_CART_ID_NOT_MATCH(
            "CP9920", "银行卡与证件不符"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP999001(
            "CP999001", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_CERTIFICATION_FAIL3(
            "CP9999", "认证失败"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CP999997(
            "CP999997", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_OP_FAIL2("CPCT9902",
            "交易失败"),
    ESCROW_JX_RESPONSE_CODE_OP_FAIL3("CPCT9903", "交易失败"),
    ESCROW_JX_RESPONSE_CODE_CERTIFICATION_ERROR(
            "CPE220E2", "数字签名或证书错"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_NO_COLLECTION_TAG(
            "CPPD20PD", "账户未加办代收付标志"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_NAME_NOT_MATCH(
            "CPPS20PS", "户名不符"),
    ESCROW_JX_RESPONSE_CODE_REQUEST_INVALID(
            "CT562800", "请求参数非法"),
    ESCROW_JX_RESPONSE_CODE_OP_TIMEOUT2(
            "CT9903", "交易超时"),
    ESCROW_JX_RESPONSE_CODE_OP_TIMEOUT3("CT990300",
            "交易超时"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_CT9904("CT9904",
            "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_G3UPC001("G3UPC001",
            "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_G3UPD001("G3UPD001",
            "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_G3UPD999("G3UPD999",
            "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_G3UPS001("G3UPS001",
            "#N/A"),
    ESCROW_JX_RESPONSE_CODE_ID_TYPE_INVALID2("JX900005",
            "证件类型错误"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_USE_INPROPERLY(
            "JX900006", "账户用途非法"),
    ESCROW_JX_RESPONSE_CODE_NCB_ERROR(
            "JX900009", "ncb系统异常"),
    ESCROW_JX_RESPONSE_CODE_REQUEST_INCOMPLETE(
            "JX900011", "请求参数不全"),
    ESCROW_JX_RESPONSE_CODE_REQUEST_TOO_LONG(
            "JX900012", "请求参数长度超长"),
    ESCROW_JX_RESPONSE_CODE_OP_REPEAT4(
            "JX900014", "交易重复"),
    ESCROW_JX_RESPONSE_CODE_FES_ERROR("JX900015",
            "FES系统验签失败"),
    ESCROW_JX_RESPONSE_CODE_INTERFACE_ONLY_FOR_PAGE_CALL(
            "JX900023", "该接口只能通过页面方式调用"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_PASSWORD_ALREADY_SET(
            "JX900024", "电子账号已设置过密码"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_PASSWORD_NOT_SET(
            "JX900025", "该电子账号未设置过密码"),
    ESCROW_JX_RESPONSE_CODE_CONTACT_BANK(
            "JX900026", "银行"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_EXISTS(
            "JX900027", "该机构此类型特殊账户已存在"),
    ESCROW_JX_RESPONSE_CODE_PAGE_SIZE_INDEX_ZERO(
            "JX900029", "当前页码和页面大小必须都大于0"),
    ESCROW_JX_RESPONSE_CODE_OP_CODE_ERROR(
            "JX900031", "交易代码错误"),
    ESCROW_JX_RESPONSE_CODE_OVER_FRENQUENCY_CONTROL(
            "JX900032", "访问频率超限"),
    ESCROW_JX_RESPONSE_CODE_DATE_INVALID2(
            "JX900041", "起始日期或结束日期不合法"),
    ESCROW_JX_RESPONSE_CODE_BILLNO_EXISTS(
            "JX900044", "订单号已存在"),
    ESCROW_JX_RESPONSE_CODE_CONTRACT_EXISTS(
            "JX900045", "签约记录已存在"),
    ESCROW_JX_RESPONSE_CODE_MOBILE_NO_INVALID(
            "JX900052", "手机号不合法"),
    ESCROW_JX_RESPONSE_CODE_BANK_CARD_LENGTH_ERROR(
            "JX900059", "银行卡号长度不够或超长"),
    ESCROW_JX_RESPONSE_CODE_BANK_CARD_CHAR_INVALID(
            "JX900060", "银行卡号存在非法字符"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_NO_FREEZE_RECORD(
            "JX900061", "该账户没有冻结资金记录"),
    ESCROW_JX_RESPONSE_CODE_DEBT_TRANSFER_OVER_HOLD(
            "JX900062", "转让债权超过现拥有的债权金额"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_FREEZE_FAIL(
            "JX900064", "该账户冻结操作未完成或失败"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_NOT_EXISTS(
            "JX900101", "账户不存在"),
    ESCROW_JX_RESPONSE_CODE_GUARANTEED_ACCOUNT_NOT_EXISTS(
            "JX900104", "标的担保账户不存在"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_NOT_EXISTS(
            "JX900121", "标的信息不存在"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_DUPLICATE(
            "JX900122", "标的号重复"),
    ESCROW_JX_RESPONSE_CODE_LENDER_AND_BORROWER_IS_IDENTICAL(
            "JX900126", "借款人和投标人是同一人"),
    ESCROW_JX_RESPONSE_CODE_ONLY_BIDDING_CAN_CANCEL(
            "JX900127", "只能撤销状态是投标中的标的"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_HAS_BID_RECORD(
            "JX900128", "该标的号存在有效的投标申请记录"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_CONTRACT_TYPE(
            "JX900130", "未知签约类型"),
    ESCROW_JX_RESPONSE_CODE_ORIGINAL_CONTRACT_NOT_EXISTS(
            "JX900131", "原签约记录不存在"),
    ESCROW_JX_RESPONSE_CODE_ORIGINAL_CONTRACT_FAIL(
            "JX900134", "原记录签约失败"),
    ESCROW_JX_RESPONSE_CODE_AUTO_INVEST_CONTRACT_WITHDRAWED(
            "JX900139", "自动投标签约记录已撤销"),
    ESCROW_JX_RESPONSE_CODE_BID_RECORD_NOT_EXIST(
            "JX900141", "投标申请记录不存在"),
    ESCROW_JX_RESPONSE_CODE_ONLY_BIDDING_OR_PROFITTING(
            "JX900143", "只能购买状态是投标中或计息中的标的"),
    ESCROW_JX_RESPONSE_CODE_AUTO_BUY_OVER_LIMIT(
            "JX900144", "自动投标签约申请金额或债权转让金额超过签约单笔金额限制"),
    ESCROW_JX_RESPONSE_CODE_AUTO_BUY_OVER_LIMIT_WHOLE(
            "JX900145", "自动投标申请总金额超过签约总金额限制"),
    ESCROW_JX_RESPONSE_CODE_ONLY_BIDDING(
            "JX900146", "只能撤销状态是投标中的投标申请"),
    ESCROW_JX_RESPONSE_CODE_BID_NOT_EXIST(
            "JX900147", "投标信息不存在"),
    ESCROW_JX_RESPONSE_CODE_BID_STATUS_ERROR(
            "JX900148", "投标信息状态不可进行债权转移"),
    ESCROW_JX_RESPONSE_CODE_BID_PROCESSING(
            "JX900168", "该投标申请对应的的融资扣款申请已存在"),
    ESCROW_JX_RESPONSE_CODE_BID_PAY_MONEY_UNMATCH(
            "JX900180", "融资扣款金额与投标申请金额不相等"),
    ESCROW_JX_RESPONSE_CODE_BID_PAY_ACCOUNT_UNMATCH(
            "JX900181", "融资扣款申请电子账户与投标申请电子账户不一致"),
    ESCROW_JX_RESPONSE_CODE_BID_STATUS_NOT_FOR_PAY(
            "JX900183", "该投标申请对应状态不能经行融资扣款"),
    ESCROW_JX_RESPONSE_CODE_OPPONENT_ACCOUNT_NOT_EXISTS(
            "JX900250", "该平台下对方电子账号不存在"),
    ESCROW_JX_RESPONSE_CODE_OP_RECORD_NOT_EXISTS(
            "JX900350", "交易信息不存在"),
    ESCROW_JX_RESPONSE_CODE_NOT_GUARANTEED_ACCOUNT(
            "JX900353", "该账号并非担保账户"),
    ESCROW_JX_RESPONSE_CODE_QUERY_TYPE_EMPTY(
            "JX900354", "查询类型对应的参数为空"),
    ESCROW_JX_RESPONSE_CODE_QUERYED_OP_NOT_EXIST(
            "JX900355", "查询交易不存在"),
    ESCROW_JX_RESPONSE_CODE_AUTHCODE_BORROWER_UNMATCH(
            "JX900361", "授权码对应借款人与请求不符"),
    ESCROW_JX_RESPONSE_CODE_AUTHCODE_LENDER_UNMATCH(
            "JX900362", "授权码对应投资人与请求不符"),
    ESCROW_JX_RESPONSE_CODE_ONLY_BIDDING_OR_PROFITTING_DEBT(
            "JX900363", "债权状态不是投标中或计息中"),
    ESCROW_JX_RESPONSE_CODE_DEBT_NOT_IN_PROFITTING_OR_REFUNDING(
            "JX900364", "债权状态不是计息中或到期待返还"),
    ESCROW_JX_RESPONSE_CODE_ORG_ID_ERROR(
            "JX900365", "未能通过机构号"),
    ESCROW_JX_RESPONSE_CODE_ORG_ID_PASS(
            "JX900366", "通过机构号"),
    ESCROW_JX_RESPONSE_CODE_OP_NOT_EXISTS(
            "JX900501", "该交易记录不存在"),
    ESCROW_JX_RESPONSE_CODE_OP_CANNOT_CANCEL(
            "JX900503", "该交易的当前状态无法撤销"),
    ESCROW_JX_RESPONSE_CODE_BATCH_CANCEL_FAIL(
            "JX900608", "该批次下并没有交易记录或只能撤销当天的批次交易"),
    ESCROW_JX_RESPONSE_CODE_BATCH_NUM_UNMATCH(
            "JX900609", "参数交易笔数或交易金额与实际数据不符"),
    ESCROW_JX_RESPONSE_CODE_BATCH_WITHDRAW_PROCESSING(
            "JX900611", "批量撤销的交易记录中存在已经集中处理的记录"),
    ESCROW_JX_RESPONSE_CODE_BATCH_NOT_EXISTS(
            "JX900612", "查询交易批次不存在"),
    ESCROW_JX_RESPONSE_CODE_MONEY_AND_INTEREST_ZERO(
            "JX900622", "还款本金和利息不能同时为0"),
    ESCROW_JX_RESPONSE_CODE_OPPONENT_ACCOUNT_EXISTS2(
            "JX900624", "对方电子账户不存在"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_WITHDRAW_DATE_ERROR(
            "JX900626", "标的撤销募集日与原募集日不符"),
    ESCROW_JX_RESPONSE_CODE_MANDATORY_FIELD_EMPTY(
            "JX900627", "必填项不能为空"),
    ESCROW_JX_RESPONSE_CODE_PRODUCT_END_DATE_INVALID(
            "JX900629", "标的登记的募集结束日期格式不正确"),
    ESCROW_JX_RESPONSE_CODE_MOBILE_NO_IDENTICAL(
            "JX900631", "新手机号与原手机号相同"),
    ESCROW_JX_RESPONSE_CODE_ACCOUNT_NOT_BELONG_TO_ORG(
            "JX900632", "该电子账号不属于该机构"),
    ESCROW_JX_RESPONSE_CODE_DATE_AND_PRODUCT_ID_ZERO(
            "JX900636", "日期和标的号不能同时为空"),
    ESCROW_JX_RESPONSE_CODE_BATCH_QUERY_NOT_USE_LAUNDRY_LIST_CODE(
            "JX900641", "查询批次类交易状态不能使用流水号"),
    ESCROW_JX_RESPONSE_CODE_NO_DATA(
            "JX900643", "未找到相关数据"),
    ESCROW_JX_RESPONSE_CODE_BORROWER_ACCOUNT_ERROR(
            "JX900647", "借款人电子账号有误"),
    ESCROW_JX_RESPONSE_CODE_BATCH_COUNT_UNMATCH(
            "JX900648", "批次处理结果条数与实际发送条数不同"),
    ESCROW_JX_RESPONSE_CODE_OP_CODE_ERROR2(
            "JX900649", "业务交易代码错误"),
    ESCROW_JX_RESPONSE_CODE_SMS_CAPTCHA_ERROR(
            "JX900650", "前导业务授权码或手机验证码错误"),
    ESCROW_JX_RESPONSE_CODE_SMS_CAPTCHA_EXISTS(
            "JX900651", "当前时间存在有效的手机验证码和业务授权码"),
    ESCROW_JX_RESPONSE_CODE_DEBT_NOT_FOR_REFUND(
            "JX900658", "债权状态不能经行还款交易"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_JX900659(
            "JX900659", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_UNKNOWN_ERROR_JX900660(
            "JX900660", "#N/A"),
    ESCROW_JX_RESPONSE_CODE_FREEZE_RECORD_WITHDRAWED(
            "JX900662", "冻结记录已经撤销"),
    ESCROW_JX_RESPONSE_CODE_FUNCTION_NOT_APPROVED3(
            "JX900663", "交易未开通"),
    ESCROW_JX_RESPONSE_CODE_OP_CANCEL_FAIL(
            "JX900676", "撤销的交易失败"),
    ESCROW_JX_RESPONSE_CODE_NO_MATCH_DATA(
            "JX900677", "未获取到相关数据"),
    ESCROW_JX_RESPONSE_CODE_FES_ERROR2(
            "JX999999", "FES系统异常"),

    USER_BANK_CARD_ALREADY_BINDED("5099", "该账户已绑卡"),

    ESCROW_JX_RESPONSE_CODE_CANNOT_UNBIND_STILL_HAVE_BID("6233", "该账户有未结的标"),

    ESCROW_JX_RESPONSE_CODE_VOUCHER_PAY_AMOUNT_ERROR("CA13", "交易金额与原交易不匹配"),
    ESCROW_JX_RESPONSE_CODE_VOUCHER_PAY_UNSUPPORTED_FUNCTION("CA40", "不支持的功能"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_ERROR("CE999042", "验证码不正确"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_INVALIDATION("CE999040", "短信验证码失效"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_EXCEPTION("CE999039", "验证码状态异常"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_NO_SEND("CE999038", "注册的手机号与发卡行预留手机号不一致"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_MORE_TIME_TO_AUTHENTICATION("CE999041", "累计验证次数过多"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_FUNCTION_NO_OPEN("CE999043", "短信验证功能未开通"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_SEND_FREQUENCY_TOO_FAST("CE999044", "短信发送频率过快"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_LESS_MONEY("9909,B3CA1013,B3CA1020,B3CAC005,B3CT1123,B3CT1135,CA51,CI64,CP512051,CP9909", "余额不足"),
    ESCROW_JX_RESPONSE_CODE_RECHARGE_ONLINE_SMS_CAPTCHA_CARD_DIFERRENT_TO_RECHARGE_CARD("CE999045", "充值卡号与短信验证卡号不一致"),
    ESCROW_JX_RESPONSE_CODE_BANK_RET_ERROR(
            "510000", "银行系统返回异常"),
    ESCROW_JX_RESPONSE_CODE_BANK_RET_SIGNATURE_ERROR(
            "510001", "银行系统返回签名校验异常"),
    ESCROW_JX_RESPONSE_CODE_BANK_REQ_SIGNATURE_ERROR(
            "510002", "请求银行系统签名异常"),
    ESCROW_JX_RESPONSE_CODE_REQ_SIGNATURE_ERROR(
            "600001", "请求签名校验异常"),
    ESCROW_JX_RESPONSE_CODE_TRANSACTION_CODE_INVALID(
            "600002", "交易代码不存在"),;


    private final String code;
    private final String desc;

    ExceptionEnum(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public static ExceptionEnum fromCode(String xcode) {
        for (ExceptionEnum ec : ExceptionEnum.values()) {
            if (xcode.equals(ec.code())) {
                return ec;
            }
        }
        return null;
    }

    public String code() {
        return code;
    }

    public String desc() {
        return desc;
    }

}