server:
    port: 8762

spring:
    application:
        name: service
    cloud:
        config:
            label: master
            profile: dev
        discovery:
            enabled: true
            service-id: config-server
#      uri: http://localhost:8888/
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    zk-nodes: localhost:2181
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include: refresh,health,bus-refresh

#
#endpoints:
#  refresh:
#    sensitive: false