spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: file://Users/allein/work/springcloud/bizcorn/config.repo
            label: master
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    zk-nodes: localhost:2181
server:
    port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include: refresh,bus-refresh