spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: file://Users/allein/work/springcloud/bizcorn/
            label: master
        stream:
            kafka:
                binder:
                    brokers: 192.168.2.233:9092
                    zk-nodes: 192.168.2.233:2181
server:
    port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12

management:
    endpoints:
        web:
            exposure:
                include: refresh,bus-refresh
logging:
    level:
        path: /data/log
        file: /config-server.log
        root: DEBUG
        allein.bizcorn.service: DEBUG
        allein.bizcorn.exception: DEBUG
