eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        registry-fetch-interval-seconds: 8

    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 4
        lease-expiration-duration-in-seconds: 12


server:
    port: 8769
spring:
    application:
        name: service-zuul
    redis:
        host: localhost
        port: 6379
        #password=bigdata123
        #database=15
        timeout: 5000
        pool:
            maxTotal: 8
            maxWaitMillis: 1000

zuul:
    routes:
        api-a:
            path: /api-ribbon/**
            serviceId: service-ribbon
            sensitiveHeaders: "*"
        api-b:
            path: /api-feign/**
            serviceId: service-feign
            sensitiveHeaders: "*"

