eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        registry-fetch-interval-seconds: 8

    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 4
        lease-expiration-duration-in-seconds: 12


server:
    port: 8769
spring:
    application:
        name: router-zuul
    redis:
        host: 192.168.2.233
        port: 6379
        #password=bigdata123
        #database=15
        timeout: 5000
        pool:
            maxTotal: 8
            maxWaitMillis: 1000

zuul:
    routes:
        api:
            path: /api/**
            serviceId: service-feign
            sensitiveHeaders: "*"
        api-common:
            path: /api-common/**
            serviceId: service
            sensitiveHeaders: "*"
#设置API网关中路由转发请求的HystrixCommand执行超时时间
hystrix:
    command:
        default:
          execution:
              isolation:
                  thread:
                      timeoutInMilliseconds: 60000
ribbon:
    ConnectTimeout: 3000 #设置路由转发请求的时候，创建请求连接的超时时间
    ReadTimeout: 60000  #用来设置路由转发请求的超时时间
